const countryCodeToName = [
  'andorra',
  'united arab emirates',
  'afghanistan',
  'antigua and barbuda',
  'anguilla',
  'albania',
  'armenia',
  'angola',
  'argentina',
  'american samoa',
  'austria',
  'australia',
  'aruba',
  'Åland islands',
  'azerbaijan',
  'bosnia and herzegovina',
  'barbados',
  'bangladesh',
  'belgium',
  'burkina faso',
  'bulgaria',
  'bahrain',
  'burundi',
  'benin',
  'saint barthélemy',
  'bermuda',
  'brunei darussalam',
  'bolivia (plurinational state of)',
  'brazil',
  'bahamas',
  'bhutan',
  'bouvet island',
  'botswana',
  'belarus',
  'belize',
  'canada',
  'cocos (keeling) islands',
  'congo (the democratic republic of the)',
  'central african republic',
  'congo',
  'switzerland',
  "côte d'ivoire",
  'cook islands',
  'chile',
  'cameroon',
  'china',
  'colombia',
  'costa rica',
  'cuba',
  'cabo verde',
  'curaçao',
  'christmas island',
  'cyprus',
  'czechia',
  'germany',
  'djibouti',
  'denmark',
  'dominica',
  'dominican republic',
  'algeria',
  'ecuador',
  'estonia',
  'egypt',
  'eritrea',
  'spain',
  'ethiopia',
  'finland',
  'fiji',
  'falkland islands (malvinas)',
  'micronesia (federated states of)',
  'faroe islands',
  'france',
  'gabon',
  'united kingdom',
  'galapagos-islands',
  'grenada',
  'georgia',
  'french guiana',
  'guernsey',
  'ghana',
  'gibraltar',
  'greenland',
  'gambia',
  'guinea',
  'guadeloupe',
  'equatorial guinea',
  'greece',
  'south georgia and the south sandwich islands',
  'guatemala',
  'guam',
  'guinea-bissau',
  'guyana',
  'hong kong',
  'heard island and mcdonald islands',
  'honduras',
  'croatia',
  'haiti',
  'hungary',
  'indonesia',
  'ireland',
  'israel',
  'isle of man',
  'india',
  'british indian ocean territory',
  'iraq',
  'iran (islamic republic of)',
  'iceland',
  'italy',
  'jersey',
  'jamaica',
  'jordan',
  'japan',
  'kenya',
  'kyrgyzstan',
  'cambodia',
  'kiribati',
  'comoros',
  'saint kitts and nevis',
  "korea (democratic people's republic of)",
  'korea (republic of)',
  'kuwait',
  'cayman islands',
  'kazakhstan',
  "lao people's democratic republic",
  'lebanon',
  'saint lucia',
  'liechtenstein',
  'sri lanka',
  'liberia',
  'lesotho',
  'lithuania',
  'luxembourg',
  'latvia',
  'libya',
  'morocco',
  'monaco',
  'moldova (republic of)',
  'montenegro',
  'madagascar',
  'marshall islands',
  'north macedonia',
  'mali',
  'myanmar',
  'mongolia',
  'macao',
  'northern mariana islands',
  'martinique',
  'mauritania',
  'montserrat',
  'malta',
  'mauritius',
  'maldives',
  'malawi',
  'mexico',
  'malaysia',
  'mozambique',
  'namibia',
  'new caledonia',
  'niger',
  'norfolk island',
  'nigeria',
  'nicaragua',
  'netherlands',
  'norway',
  'nepal',
  'nauru',
  'niue',
  'new zealand',
  'oman',
  'panama',
  'peru',
  'french polynesia',
  'papua new guinea',
  'philippines',
  'pakistan',
  'poland',
  'saint pierre and miquelon',
  'pitcairn',
  'puerto rico',
  'palestine, state of',
  'portugal',
  'palau',
  'paraguay',
  'qatar',
  'réunion',
  'romania',
  'serbia',
  'russian federation',
  'rwanda',
  'saudi arabia',
  'solomon islands',
  'seychelles',
  'sudan',
  'sweden',
  'singapore',
  'slovenia',
  'svalbard and jan mayen',
  'slovakia',
  'sierra leone',
  'san marino',
  'senegal',
  'somalia',
  'suriname',
  'south sudan',
  'sao tome and principe',
  'el salvador',
  'sint maarten',
  'syrian arab republic',
  'eswatini',
  'turks and caicos islands',
  'chad',
  'french southern territories',
  'togo',
  'thailand',
  'tajikistan',
  'tokelau',
  'timor-leste',
  'turkmenistan',
  'tunisia',
  'tonga',
  'turkey',
  'trinidad and tobago',
  'tuvalu',
  'taiwan',
  'tanzania, united republic of',
  'ukraine',
  'uganda',
  'united states minor outlying islands',
  'united states',
  'uruguay',
  'uzbekistan',
  'holy see',
  'saint vincent and the grenadines',
  'venezuela (bolivarian republic of)',
  'virgin islands (british)',
  'virgin islands (u.s.)',
  'viet nam',
  'vanuatu',
  'wallis and futuna',
  'samoa',
  'kosovo',
  'yemen',
  'mayotte',
  'south africa',
  'zambia',
  'zimbabwe',
  'european union',
  'england',
  'northern ireland',
  'scotland',
  'wales',
  'shetland',
  'california',
];

export default countryCodeToName;
